services:
  vrising:
    image: trueosiris/vrising
    environment:
      - TZ=Europe/Helsinki
      - SERVERNAME=paras-server
    volumes:
      - type: bind
        source: "./data/vrising/server"
        target: /mnt/vrising/server
        bind:
          create_host_path: true
      - type: bind
        source: "./data/vrising/persistentdata"
        target: /mnt/vrising/persistentdata
        bind:
          create_host_path: true
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge